version: '3'
services:
    # app:
    #     container_name: catalog-write
    #     build:
    #         target: builder
    #         context: .
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - ./src:/app/src
    #     env_file:
    #         - .env
    #     command: npm run start:dev
    # redis:
    #     image: redis:6.0.9
    #     container_name: redis
    #     restart: always
    #     ports:
    #         - 6379:6379
    #     command: redis-server --appendonly yes
    zookeeper:
        image: confluentinc/cp-zookeeper:5.0.0
        container_name: zookeeper
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        depends_on:
            - kafka
        ports:
            - 9021:8080
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_CLUSTERS_0_PROPERTIES_SECURITYPROTOCOL: PLAINTEXT
            KAFKA_CLUSTERS_0_PROPERTIES_SASLMECHANISM: PLAIN
            KAFKA_CLUSTERS_0_PROPERTIES_SASLJAASSCHEMA: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin
